/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as customerIndexRouteImport } from './routes/(customer)/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as customerWishlistRouteImport } from './routes/(customer)/wishlist'
import { Route as customerSignupRouteImport } from './routes/(customer)/signup'
import { Route as customerSigninRouteImport } from './routes/(customer)/signin'
import { Route as customerShopRouteImport } from './routes/(customer)/shop'
import { Route as customerProfileRouteImport } from './routes/(customer)/profile'
import { Route as customerProductDetailRouteImport } from './routes/(customer)/product-detail'
import { Route as customerOrderTrackRouteImport } from './routes/(customer)/order-track'
import { Route as customerCheckoutRouteImport } from './routes/(customer)/checkout'
import { Route as customerCartRouteImport } from './routes/(customer)/cart'
import { Route as customerLayoutRouteImport } from './routes/(customer)/_layout'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const customerIndexRoute = customerIndexRouteImport.update({
  id: '/(customer)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/admin/delivery',
  path: '/admin/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const customerWishlistRoute = customerWishlistRouteImport.update({
  id: '/(customer)/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const customerSignupRoute = customerSignupRouteImport.update({
  id: '/(customer)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const customerSigninRoute = customerSigninRouteImport.update({
  id: '/(customer)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const customerShopRoute = customerShopRouteImport.update({
  id: '/(customer)/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const customerProfileRoute = customerProfileRouteImport.update({
  id: '/(customer)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const customerProductDetailRoute = customerProductDetailRouteImport.update({
  id: '/(customer)/product-detail',
  path: '/product-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const customerOrderTrackRoute = customerOrderTrackRouteImport.update({
  id: '/(customer)/order-track',
  path: '/order-track',
  getParentRoute: () => rootRouteImport,
} as any)
const customerCheckoutRoute = customerCheckoutRouteImport.update({
  id: '/(customer)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const customerCartRoute = customerCartRouteImport.update({
  id: '/(customer)/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const customerLayoutRoute = customerLayoutRouteImport.update({
  id: '/(customer)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/cart': typeof customerCartRoute
  '/checkout': typeof customerCheckoutRoute
  '/order-track': typeof customerOrderTrackRoute
  '/product-detail': typeof customerProductDetailRoute
  '/profile': typeof customerProfileRoute
  '/shop': typeof customerShopRoute
  '/signin': typeof customerSigninRoute
  '/signup': typeof customerSignupRoute
  '/wishlist': typeof customerWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof customerIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/cart': typeof customerCartRoute
  '/checkout': typeof customerCheckoutRoute
  '/order-track': typeof customerOrderTrackRoute
  '/product-detail': typeof customerProductDetailRoute
  '/profile': typeof customerProfileRoute
  '/shop': typeof customerShopRoute
  '/signin': typeof customerSigninRoute
  '/signup': typeof customerSignupRoute
  '/wishlist': typeof customerWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof customerIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/(customer)/_layout': typeof customerLayoutRoute
  '/(customer)/cart': typeof customerCartRoute
  '/(customer)/checkout': typeof customerCheckoutRoute
  '/(customer)/order-track': typeof customerOrderTrackRoute
  '/(customer)/product-detail': typeof customerProductDetailRoute
  '/(customer)/profile': typeof customerProfileRoute
  '/(customer)/shop': typeof customerShopRoute
  '/(customer)/signin': typeof customerSigninRoute
  '/(customer)/signup': typeof customerSignupRoute
  '/(customer)/wishlist': typeof customerWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/(customer)/': typeof customerIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/cart'
    | '/checkout'
    | '/order-track'
    | '/product-detail'
    | '/profile'
    | '/shop'
    | '/signin'
    | '/signup'
    | '/wishlist'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/cart'
    | '/checkout'
    | '/order-track'
    | '/product-detail'
    | '/profile'
    | '/shop'
    | '/signin'
    | '/signup'
    | '/wishlist'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/$'
    | '/(customer)/_layout'
    | '/(customer)/cart'
    | '/(customer)/checkout'
    | '/(customer)/order-track'
    | '/(customer)/product-detail'
    | '/(customer)/profile'
    | '/(customer)/shop'
    | '/(customer)/signin'
    | '/(customer)/signup'
    | '/(customer)/wishlist'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/(customer)/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  customerLayoutRoute: typeof customerLayoutRoute
  customerCartRoute: typeof customerCartRoute
  customerCheckoutRoute: typeof customerCheckoutRoute
  customerOrderTrackRoute: typeof customerOrderTrackRoute
  customerProductDetailRoute: typeof customerProductDetailRoute
  customerProfileRoute: typeof customerProfileRoute
  customerShopRoute: typeof customerShopRoute
  customerSigninRoute: typeof customerSigninRoute
  customerSignupRoute: typeof customerSignupRoute
  customerWishlistRoute: typeof customerWishlistRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  customerIndexRoute: typeof customerIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/': {
      id: '/(customer)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof customerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/wishlist': {
      id: '/(customer)/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof customerWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/signup': {
      id: '/(customer)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof customerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/signin': {
      id: '/(customer)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof customerSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/shop': {
      id: '/(customer)/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof customerShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/profile': {
      id: '/(customer)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof customerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/product-detail': {
      id: '/(customer)/product-detail'
      path: '/product-detail'
      fullPath: '/product-detail'
      preLoaderRoute: typeof customerProductDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/order-track': {
      id: '/(customer)/order-track'
      path: '/order-track'
      fullPath: '/order-track'
      preLoaderRoute: typeof customerOrderTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/checkout': {
      id: '/(customer)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof customerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/cart': {
      id: '/(customer)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof customerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/_layout': {
      id: '/(customer)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof customerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  customerLayoutRoute: customerLayoutRoute,
  customerCartRoute: customerCartRoute,
  customerCheckoutRoute: customerCheckoutRoute,
  customerOrderTrackRoute: customerOrderTrackRoute,
  customerProductDetailRoute: customerProductDetailRoute,
  customerProfileRoute: customerProfileRoute,
  customerShopRoute: customerShopRoute,
  customerSigninRoute: customerSigninRoute,
  customerSignupRoute: customerSignupRoute,
  customerWishlistRoute: customerWishlistRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  customerIndexRoute: customerIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
